version: "3.3"
services:

  web:
    build: .
    image: amazonlinux:flask-app
    container_name: flask-app
    ports:
      - "80:4000"
    volumes:
      - ./app:/home/ec2-user/app/app/
    entrypoint: ["gunicorn", "-b", "0.0.0.0:4000", "app:app"]
